package net.cu5tmtp.GregECore.gregstuff.GregMachines;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.IMachineBlockEntity;
import com.gregtechceu.gtceu.api.machine.MachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.common.data.GCYMBlocks;
import net.cu5tmtp.GregECore.gregstuff.GregMachines.parts.RealityFractureEnginePartMachine;
import net.cu5tmtp.GregECore.gregstuff.GregMachines.renderer.renderRegistries.GregERenederRegistries;
import net.cu5tmtp.GregECore.gregstuff.GregUtils.notCoreStuff.GregERecipeTypes;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;
import org.jetbrains.annotations.NotNull;
import java.util.List;

import static com.gregtechceu.gtceu.api.pattern.Predicates.blocks;
import static com.gregtechceu.gtceu.common.data.models.GTMachineModels.createWorkableCasingMachineModel;
import static net.cu5tmtp.GregECore.gregstuff.GregUtils.GregECore.REGISTRATE;

public class RealityFractureEngine extends WorkableElectricMultiblockMachine{

    public RealityFractureEngine(IMachineBlockEntity holder, Object... args) {
        super(holder, args);
    }
    public static MachineDefinition REALITYFRACTUREENGINE = REGISTRATE
            .multiblock("realityfractureengine", RealityFractureEngine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(GregERecipeTypes.OPEN_THE_RIFT)
            .appearanceBlock(GCYMBlocks.CASING_ATOMIC)
            .pattern(definition -> {
                return FactoryBlockPattern.start()
                        .aisle("aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaacbbbcaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacaaacaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaeaaaeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacaaacaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacbbbcaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbabbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebaaabeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacaaacaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabahabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaiagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaiagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabahabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbabbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebaaabeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacaaacaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebaaabeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacbbbcaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabkbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaglgaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacbbbcaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacjcaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacjcaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaamalamaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaamalamaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaamalamaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaamalamaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aacccaaaaaaaaaaaaacccccaaaaaaaaaaaaacccaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aacccaaaaaaaaaaaaabbbbbaaaaaaaaaaaaacccaa", "aaaaaaaaaaaaaaaaaaacjcaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaabbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabgggbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaeglgeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabgggbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaacjcaaaaaaaaaaaaaaaaaaa", "aacccaaaaaaaaaaaaabbbbbaaaaaaaaaaaaacccaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaababbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aacccaaaaaaaaaaaaacccccaaaaaaaaaaaaacccaa")
                        .aisle("acbbbcaaaaaaaaaaacbbbbbcaaaaaaaaaaacbbbca", "abaaabaaabbbbaaaabaaaaabaaaabbbbaaabaaaba", "abbbbbabbbmmbbbaabaaaaabaabbbmmbbbabbbbba", "abaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaba", "abaaabbbbaaaabbbbbaaaaabbbbbaaaabbbbaaaba", "abaaabbaaaaaaaabbbaaaaabbbaaaaaaaabbaaaba", "acaaacaaaaaaaaaaabaaaaabaaaaaaaaaaacaaaca", "aabcbaaaaaaaaaaaaacbbbcaaaaaaaaaaaaabcbaa", "aebbbeaaaaaaaaaaaaabjbaaaaaaaaaaaaaebbbea", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aabbbaaaaaaaaaaaaabaaabbaaaaaaaaaaaabbbaa", "aagggaaaaaaaaaaaabaaaaabaaaaaaaaaaaagggaa", "aagggaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaagggaa", "aagggaaaaaaaaaaaabaaaaabaaaaaaaaaaaagggaa", "aabbbaaaaaaaaaaaaabaaabaaaaaaaaaaaaabbbaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aabcbaaaaaaaaaaaaacbbbcaaaaaaaaaaaaabcbaa", "acaaacaaaaaaaaaaabaaaaabaaaaaaaaaaacaaaca", "abaaabbaaaaaaaabbbaaaaabbbaaaaaaaabbaaaba", "abaaabbbbaaaabbbbbaaaaabbbbbaaaabbbbaaaba", "abaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaba", "abaaababbbmmbbbaabbaaaabaabbbmmbbbabbbbba", "abaaabaaabbbbaaaabaaaaabaaaabbbbaaabaaaba", "acbbbcaaaaaaaaaaacbbbbbcaaaaaaaaaaacbbbca")
                        .aisle("cbbbbcaaabbbbaaaacbbbbbcaaaabbbbaaacbbbbc", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "bbbbbbbaaaaaaaabbbaanaabbbaaaaaaaabbbbbbb", "baaaabaaaaaaaaaaabaanaabaaaaaaaaaaabaaaab", "baaaabaaabbbbaaaabaanaabaaaabbbbaaabaaaab", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "caaaabcaaaaaaaabbbaanaabbbaaaaaaaabcaaaac", "abbbbbaaaaaaaaaaacbbbbbcaaaaaaaaaaabbbbba", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "afbbbfaaaaaaaaaaaafbbbfaaaaaaaaaaaafbbbfa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "abaaabaaaaaaaaaaabaaaaabaaaaaaaaaaabaaaba", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "abaaabaaaaaaaaaaabaaaaabaaaaaaaaaaabaaaba", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "abbbbbaaaaaaaaaaacbbbbbcaaaaaaaaaaabbbbba", "caaaaacaaaaaaaabbbaanaabbbaaaaaaaabcaaaac", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "baaaabaaabbbbaaaabaanaabaaaabbbbaaabaaaab", "baaaabaaaaaaaaaaabaanaabaaaaaaaaaaabaaaab", "baaaabbaaaaaaaabbbaanaabbbaaaaaaaabbbbbbb", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "cbbbbcaaabbbbaaaacbbbbbcaaaabbbbaaacbbbbc")
                        .aisle("cbbbbcaaajjjjaaaacbbbbbcaaaajjjjaaacbbbbc", "caaaabajjaaaajjaabannnabaajjaaaajjabaaaac", "cbbbbbjaallllaajjbannnabjjaallllaajbbbbbc", "caaaaballaaaallaabannnabaallaaaallabaaaac", "caaaablaajjjjaallbannnabllaajjjjaalbaaaac", "caaaabajjaaaajjaabannnabaajjaaaajjabaaaac", "caaaabjaaaaaaaajjbannnabjjaaaaaaaajcaaaac", "acbbbjaaaaaaaaaaajbbbbbjaaaaaaaaaaajbbbca", "ebaaabeaaaaaaaaaaajaaajaaaaaaaaaaaebaaabe", "afbbbfaaaaaaaaaaaafbbbfaaaaaaaaaaaafbbbfa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "abahakaaaaaaaaaaabaaaaabaaaaaaaaaaakahaba", "agaiagaaaaaaaaaaagaaaaagaaaaaaaaaaagaiaga", "agaaalaaaaaaaaaaalaaaaalaaaaaaaaaaalaaaga", "agaiagaaaaaaaaaaagaaaaagaaaaaaaaaaagaiaga", "abahabaaaaaaaaaaabaaaaabaaaaaaaaaaabahaba", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "acbbbbaaaaaaaaaaajbbbbbjaaaaaaaaaaajbbbca", "caaaaajaaaaaaaajjbannnabjjaaaaaaaajcaaaac", "caaaabajjaaaajjaabannnabaajjaaaajjabaaaac", "caaaablaajjjjaallbannnabllaajjjjaalbaaaac", "caaaaballaaaallaabannnabaallaaaallabaaaac", "caaaabjaallllaajjbannnabjjaallllaajbbbbbc", "caaaabajjaaaajjaabannnabaajjaaaajjabaaaac", "cbbbbcaaajjjjaaaacbbbbbcaaaajjjjaaacbbbbc")
                        .aisle("cbbbbcaaabbbbaaaacbbbbbcaaaabbbbaaacbbbbc", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "bbbbbbbaaaaaaaabbbaanaabbbaaaaaaaabbbbbbb", "baaaabaaaaaaaaaaabaanaabaaaaaaaaaaabaaaab", "baaaabaaabbbbaaaabaanaabaaaabbbbaaabaaaab", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "caaaabcaaaaaaaabbbaanaabbbaaaaaaaabcaaaac", "abbbbbaaaaaaaaaaacbbbbbcaaaaaaaaaaabbbbba", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "afbbbfaaaaaaaaaaaafbbbfaaaaaaaaaaaafbbbfa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "abaaabaaaaaaaaaaabaaaaabaaaaaaaaaaabaaaba", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "abaaabaaaaaaaaaaabaaaaabaaaaaaaaaaabaaaba", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "abbbbbaaaaaaaaaaacbbbbbcaaaaaaaaaaabbbbba", "caaaaacaaaaaaaabbbaanaabbbaaaaaaaabcaaaac", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "baaaabaaabbbbaaaabaanaabaaaabbbbaaabaaaab", "baaaabaaaaaaaaaaabaanaabaaaaaaaaaaabaaaab", "baaaabbaaaaaaaabbbaanaabbbaaaaaaaabbbbbbb", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "cbbbbcaaabbbbaaaacbbbbbcaaaabbbbaaacbbbbc")
                        .aisle("acbbbcaaaaaaaaaaacbbbbbcaaaaaaaaaaacbbbca", "abaaabaaabbbbaaaabaaaaabaaaabbbbaaabaaaba", "abbbbbabbbmmbbbaabaaaaabaabbbmmbbbabbbbba", "abaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaba", "abaaabbbbaaaabbbbbaaaaabbbbbaaaabbbbaaaba", "abaaabbaaaaaaaabbbaaaaabbbaaaaaaaabbaaaba", "acaaacaaaaaaaaaaabaaaaabaaaaaaaaaaacaaaca", "aabcbaaaaaaaaaaaaacbbbcaaaaaaaaaaaaabcbaa", "aebbbeaaaaaaaaaaaaabjbaaaaaaaaaaaaaebbbea", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aabbbaaaaaaaaaaaaabaaabaaaaaaaaaaaaabbbaa", "aagggaaaaaaaaaaaabaaaaabaaaaaaaaaaaagggaa", "aagggaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaagggaa", "aagggaaaaaaaaaaaabaaaaabaaaaaaaaaaaagggaa", "aabbbaaaaaaaaaaaaabaaabaaaaaaaaaaaaabbbaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aabcbaaaaaaaaaaaaacbbbcaaaaaaaaaaaaabcbaa", "acaaacaaaaaaaaaaabaaaaabaaaaaaaaaaacaaaca", "abaaabbaaaaaaaabbbaaaaabbbaaaaaaaabbaaaba", "abaaabbbbaaaabbbbbaaaaabbbbbaaaabbbbaaaba", "abaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaba", "abaaababbbmmbbbaabaaaaabaabbbmmbbbabbbbba", "abaaabaaabbbbaaaabaaaaabaaaabbbbaaabaaaba", "acbbbcaaaaaaaaaaacbbbbbcaaaaaaaaaaacbbbca")
                        .aisle("aacccaaaaaaaaaaaaacbbbcaaaaaaaaaaaaacccaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aacccaaaaaaaaaaaaacaaacaaaaaaaaaaaaacccaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaeaaaeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aacccaaaaaaaaaaaaacaaacaaaaaaaaaaaaacccaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aacccaaaaaaaaaaaaacbbbcaaaaaaaaaaaaacccaa")
                        .aisle("aaaaaaaaaaaaaaaaaaacocaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("minecraft:air"))))
                        .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:atomic_casing"))))
                        .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:high_temperature_smelting_casing"))))
                        .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:large_scale_assembler_casing"))))
                        .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gregecore:awakened_draconium_coil"))))
                        .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:cleanroom_glass"))))
                        .where("h", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_gearbox"))))
                        .where("i", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("minecraft:iron_bars"))))
                        .where("j", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:industrial_steam_casing"))))
                        .where("k", Predicates.abilities(RealityFractureEnginePartMachine.getPartAbility()).setMaxGlobalLimited(3).setPreviewCount(3))
                        .where("l", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:fusion_coil"))))
                        .where("m", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:fusion_glass"))))
                        .where("n", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:superconducting_coil"))))
                        .where("o", Predicates.controller(blocks(definition.getBlock())))
                        .build();
            })
            .model(createWorkableCasingMachineModel(
                    GTCEu.id("block/casings/gcym/high_temperature_smelting_casing"),
                    GTCEu.id("block/multiblock/fusion_reactor"))
                    .andThen(b -> b.addDynamicRenderer(GregERenederRegistries::createRealityEngineRender)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Material Compressing").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("You have done it. You made a machine capable of making and sustaining stars. While some might say its useful for energy," +
                    " you have different ideas. Using the immense gravitational forces inside a stars core, you just might forge unthinkable items.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Star starts with 1 x 10³⁰ tons. If your star drops below 0 or over 500 x 10³⁰ tons, the multiblock explodes. Each crafting recipe has some sort of weight cost," +
                    " due to the star fusing some of its own weight into it whenever it forms a singularity. " +
                    "You can increase the weight of the star if you feed it correct items. The correct items are shown below with their weight value. Place them in the Star Feeder.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Brass Pellet: 0.1 x 10³⁰ tons").withStyle(ChatFormatting.LIGHT_PURPLE))
            .tooltips(Component.literal("Americium Pellet: 3 x 10³⁰ tons").withStyle(ChatFormatting.LIGHT_PURPLE))
            .tooltips(Component.literal("Neutronium Pellet: 10 x 10³⁰ tons").withStyle(ChatFormatting.LIGHT_PURPLE))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Controller emits redstone: ").withStyle(ChatFormatting.GOLD)
                    .append(Component.literal("1 redstone strength").withStyle(ChatFormatting.RED))
                    .append(Component.literal(" per ").withStyle(style -> style.withColor(0x90EE90)))
                    .append(Component.literal("30 x 10³⁰").withStyle(ChatFormatting.RED))
                    .append(Component.literal(" tons.").withStyle(style -> style.withColor(0x90EE90))))
            .register();

    @Override
    public void addDisplayText(@NotNull List<Component> textList) {
        super.addDisplayText(textList);
    }

    public static void init() {
    }
}
