package net.cu5tmtp.GregECore.gregstuff.GregMachines;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.IMachineBlockEntity;
import com.gregtechceu.gtceu.api.machine.MachineDefinition;
import com.gregtechceu.gtceu.api.machine.feature.IRedstoneSignalMachine;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.api.recipe.GTRecipe;
import com.gregtechceu.gtceu.common.data.GCYMBlocks;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;
import com.lowdragmc.lowdraglib.gui.widget.LabelWidget;
import com.lowdragmc.lowdraglib.gui.widget.TextFieldWidget;
import com.lowdragmc.lowdraglib.gui.widget.Widget;
import com.lowdragmc.lowdraglib.gui.widget.WidgetGroup;
import com.lowdragmc.lowdraglib.syncdata.annotation.DescSynced;
import com.lowdragmc.lowdraglib.syncdata.annotation.Persisted;
import com.lowdragmc.lowdraglib.syncdata.field.ManagedFieldHolder;
import net.cu5tmtp.GregECore.gregstuff.GregMachines.renderer.renderRegistries.GregERenederRegistries;
import net.cu5tmtp.GregECore.gregstuff.GregUtils.notCoreStuff.GregERecipeTypes;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.List;

import static com.gregtechceu.gtceu.api.pattern.Predicates.blocks;
import static com.gregtechceu.gtceu.common.data.models.GTMachineModels.createWorkableCasingMachineModel;
import static net.cu5tmtp.GregECore.gregstuff.GregUtils.GregECore.REGISTRATE;

public class SpaceElevator extends WorkableElectricMultiblockMachine implements IRedstoneSignalMachine {

    public SpaceElevator(IMachineBlockEntity holder, Object... args) {
        super(holder, args);
    }

    protected static final ManagedFieldHolder MANAGED_FIELD_HOLDER = new ManagedFieldHolder(
            SpaceElevator.class,
            WorkableElectricMultiblockMachine.MANAGED_FIELD_HOLDER);

    @Override
    public ManagedFieldHolder getFieldHolder() {
        return MANAGED_FIELD_HOLDER;
    }

    @DescSynced
    @Persisted
    protected int targetHeight = 0;

    private int recipeHeight = 0;

    @Override
    public Widget createUIWidget() {
        Widget widget = super.createUIWidget();

        if (widget instanceof WidgetGroup group) {

            group.addWidget(new LabelWidget(-80, 125, Component.literal("Target Height:").withStyle(ChatFormatting.GOLD)));

            var frequencyInput = new TextFieldWidget(
                    -70, 140, 60, 12,
                    () -> this.targetHeight == 0 ? "" : String.valueOf(this.targetHeight),
                    val -> {
                        if (val.isEmpty()) {
                            this.targetHeight = 0;
                        } else {
                            try {
                                this.targetHeight = Integer.parseInt(val);
                            } catch (NumberFormatException ignored) {
                            }
                        }
                    }
            );
            group.addWidget(frequencyInput);
        }
        return widget;
    }

    @Override
    public boolean beforeWorking(@Nullable GTRecipe recipe) {

        assert recipe != null;
        recipeHeight = recipe.data.getInt("height_level");

        if(targetHeight > recipeHeight || targetHeight < (recipeHeight - 10)) {
            return false;
        }

        return super.beforeWorking(recipe);
    }

    public static MachineDefinition SPACE_ELEVATOR = REGISTRATE
            .multiblock("spaceelevator", SpaceElevator::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(GregERecipeTypes.SEND_UP_THE_MATS)
            .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_ATOMIC)
            .pattern(definition -> {
                return FactoryBlockPattern.start()
                        .aisle("bbbbbbbbbbbbaaaaaaabbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbbbbbaaacccccccaaabbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbbbaaccacccccccaccaabbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbbaacccacccccccacccaabbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbacccccacccccccacccccabbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbacccccccacccccacccccccabbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbaccccccccacccccaccccccccabbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbaaccccccaaaaaaaaaaaccccccaabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbaccccccacccacccacccaccccccabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbgggggggbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("baccccccaccccacccaccccaccccccab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbggbbbbbbbggbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbgggggggbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bacccccacccccacccacccccacccccab", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbgbbbbbbbbbbbgbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbgbbbbbbbgbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbgggggggbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("baaaaccaccccccacaccccccaccaaaab", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbibbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbgbbbbbbbbbbbgbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbgbbbbbbbbbgbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbgbbbbbbbgbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbgggggbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb")
                        .aisle("accccaaaccccccacaccccccaaacccca", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbibbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbgbbbbbbbbbbbbbgbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbgbbbbbbbbbbbgbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbgbbbbbbbbbgbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbgbbbbbgbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("accccccaaaaccccjccccaaaacccccca", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbgbbbbbbbbbbbbbgbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbgbbbbbbbbbbbgbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbgbbbbbbbbbgbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbgbbbbbbbgbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("accccccacccaaccjccaacccacccccca", "bbdddddbbbbbbbbbbbbbbbbbdddddbb", "bbbdffdbbbbbbbbbbbbbbbbbdffdbbb", "bbbddfdbbbbbbbbbbbbbbbbbdfddbbb", "bbbbdfdbbbbbbbbbbbbbbbbbdfdbbbb", "bbbbdfdbbbbbbbhhhbbbbbbbdfdbbbb", "bbbbdfdbbbbbbbhbhbbbbbbbdfdbbbb", "bbbbdfdbbbbbbbhbhbbbbbbbdfdbbbb", "bbbbdfdbbbbbbbbbbbbbbbbbdfdbbbb", "bbbbbdfdbbbbbbbbbbbbbbbdfdbbbbb", "bbbbbdfdbbbbbbbbbbbbbbbdfdbbbbb", "bbbbbdfdbbbbbbbbbbbbbbbdfdbbbbb", "bbbbbdfdbbbbbbbbbbbbbbbdfdbbbbb", "bbbbbdfdgbbbbbbbbbbbbbgdfdbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdgbbbbbbbbbbbgdfdbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdgbbbbbbbbbgdfdbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdgbbbbbbbgdfdbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdddbbbbbbbdddbbbbbbbbb", "bbbbbbbbbbddbbbbbbbddbbbbbbbbbb", "bbbbbbbbbbddbbbbbbbddbbbbbbbbbb", "bbbbbbbbbbbdbbbbbbbdbbbbbbbbbbb", "bbbbbbbbbbbdbbbbbbbdbbbbbbbbbbb")
                        .aisle("accccccacccccjjejjcccccacccccca", "bbbeeebbbbhhhbbjbbhhhbbbbeeebbb", "bbbbeebbbbbihbbjbbhibbbbbeebbbb", "bbbbbebbbbbbhbbbbbhbbbbbbebbbbb", "bbbbbebbbbbbhbbbbbhbbbbbbebbbbb", "bbbbbebbbbbbihhbhhibbbbbbebbbbb", "bbbbbebbbbbbbbbbbbbbbbbbbebbbbb", "bbbbbebbbbbbbbbbbbbbbbbbbebbbbb", "bbbbbebbbbbbbbbbbbbbbbbbbebbbbb", "bbbbbbebbbbbbbbbbbbbbbbbebbbbbb", "bbbbbbebbbbbbbbbbbbbbbbbebbbbbb", "bbbbbbebbbbbbbbbbbbbbbbbebbbbbb", "bbbbbbebbbbbbbbbbbbbbbbbebbbbbb", "bbbbbbebgbbbbbbbbbbbbbgbebbbbbb", "bbbbbbbebbbbbbbbbbbbbbbebbbbbbb", "bbbbbbbebbbbbbbbbbbbbbbebbbbbbb", "bbbbbbbebbbbbbbbbbbbbbbebbbbbbb", "bbbbbbbebbbbbbbbbbbbbbbebbbbbbb", "bbbbbbbebbbbbbbbbbbbbbbebbbbbbb", "bbbbbbbebgbbbbbbbbbbbgbebbbbbbb", "bbbbbbbbebbbbbbbbbbbbbebbbbbbbb", "bbbbbbbbebbbbbbbbbbbbbebbbbbbbb", "bbbbbbbbebbbbbbbbbbbbbebbbbbbbb", "bbbbbbbbebbbbbbbbbbbbbebbbbbbbb", "bbbbbbbbebbbbbbbbbbbbbebbbbbbbb", "bbbbbbbbebbbbbbbbbbbbbebbbbbbbb", "bbbbbbbbebgbbbbbbbbbgbebbbbbbbb", "bbbbbbbbbebbbbbbbbbbbebbbbbbbbb", "bbbbbbbbbebbbbbbbbbbbebbbbbbbbb", "bbbbbbbbbebbbbbbbbbbbebbbbbbbbb", "bbbbbbbbbebbbbbbbbbbbebbbbbbbbb", "bbbbbbbbbebbbbbbbbbbbebbbbbbbbb", "bbbbbbbbbebbbbbbbbbbbebbbbbbbbb", "bbbbbbbbbebbbbbbbbbbbebbbbbbbbb", "bbbbbbbbbebbbbbbbbbbbebbbbbbbbb", "bbbbbbbbbebgbbbbbbbgbebbbbbbbbb", "bbbbbbbbbbebbbbbbbbbebbbbbbbbbb", "bbbbbbbbbbebbbbbbbbbebbbbbbbbbb", "bbbbbbbbbbebbbbbbbbbebbbbbbbbbb", "bbbbbbbbbbebbbbbbbbbebbbbbbbbbb", "bbbbbbbbbbebbbbbbbbbebbbbbbbbbb", "bbbbbbbbbbebbbbbbbbbebbbbbbbbbb", "bbbbbbbbbbbebbbbbbbebbbbbbbbbbb", "bbbbbbbbbbbebbbbbbbebbbbbbbbbbb", "bbbbbbbbbbbebbbbbbbebbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("accccccacccaaccjccaacccacccccca", "bbdddddbbbbbbbbbbbbbbbbbdddddbb", "bbbdffdbbbbbbbbbbbbbbbbbdffdbbb", "bbbddfdbbbbbbbbbbbbbbbbbdfddbbb", "bbbbdfdbbbbbbbbbbbbbbbbbdfdbbbb", "bbbbdfdbbbbbbbhhhbbbbbbbdfdbbbb", "bbbbdfdbbbbbbbhbhbbbbbbbdfdbbbb", "bbbbdfdbbbbbbbhbhbbbbbbbdfdbbbb", "bbbbdfdbbbbbbbbbbbbbbbbbdfdbbbb", "bbbbbdfdbbbbbbbbbbbbbbbdfdbbbbb", "bbbbbdfdbbbbbbbbbbbbbbbdfdbbbbb", "bbbbbdfdbbbbbbbbbbbbbbbdfdbbbbb", "bbbbbdfdbbbbbbbbbbbbbbbdfdbbbbb", "bbbbbdfdgbbbbbbbbbbbbbgdfdbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdbbbbbbbbbbbbbdfdbbbbbb", "bbbbbbdfdgbbbbbbbbbbbgdfdbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdbbbbbbbbbbbdfdbbbbbbb", "bbbbbbbdfdgbbbbbbbbbgdfdbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdbbbbbbbbbdfdbbbbbbbb", "bbbbbbbbdfdgbbbbbbbgdfdbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdfdbbbbbbbdfdbbbbbbbbb", "bbbbbbbbbdddbbbbbbbdddbbbbbbbbb", "bbbbbbbbbbddbbbbbbbddbbbbbbbbbb", "bbbbbbbbbbddbbbbbbbddbbbbbbbbbb", "bbbbbbbbbbbdbbbbbbbdbbbbbbbbbbb", "bbbbbbbbbbbdbbbbbbbdbbbbbbbbbbb")
                        .aisle("accccccaaaaccccjccccaaaacccccca", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbgbbbbbbbbbbbbbgbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbgbbbbbbbbbbbgbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbgbbbbbbbbbgbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbgbbbbbbbgbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("accccaaaccccccacaccccccaaacccca", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbibbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbgbbbbbbbbbbbbbgbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbgbbbbbbbbbbbgbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbgbbbbbbbbbgbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbgbbbbbgbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("baaaaccaccccccacaccccccaccaaaab", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbibbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbgbbbbbbbbbbbgbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbgbbbbbbbbbgbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbgbbbbbbbgbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbgggggbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb")
                        .aisle("bacccccacccccacccacccccacccccab", "bbbbbbbbbbbbbbbhbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbgbbbbbbbbbbbgbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbgbbbbbbbgbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbgggggggbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("baccccccaccccacccaccccaccccccab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbggbbbbbbbggbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbgggggggbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbaccccccacccacccacccaccccccabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbgggggggbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbaaccccccaaaaaaaaaaaccccccaabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbaccccccccacccccaccccccccabbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbacccccccacccccacccccccabbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbacccccacccccccacccccabbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbfefbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbbaacccacccccccacccaabbbbbb", "bbbbbbbbbbbbbbdedbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbbbaaccacccccccaccaabbbbbbb", "bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbbbbbaaacccccccaaabbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        .aisle("bbbbbbbbbbbbaaakaaabbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")

                        .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stress_proof_casing")))
                                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1)))
                        .where("b", Predicates.any())
                        .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                        .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:large_scale_assembler_casing"))))
                        .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:nonconducting_casing"))))
                        .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:clean_machine_casing"))))
                        .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:hastelloy_c_276_frame"))))
                        .where("h", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:shock_proof_cutting_casing"))))
                        .where("i", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gregecore:shockproof_engine"))))
                        .where("j", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:assembly_line_unit"))))
                        .where('k', Predicates.controller(blocks(definition.getBlock())))
                        .build();
            })
            .model(createWorkableCasingMachineModel(
                    GTCEu.id("block/casings/gcym/stress_proof_casing"),
                    GTCEu.id("block/multiblock/fusion_reactor"))
                    .andThen(b -> b.addDynamicRenderer(GregERenederRegistries::createSpaceElevatorRender)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Orbital Extraction").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("No longer a theoretical concept, the Space Elevator bridges the gap between planetary surface and orbit. " +
                    "Use it to accelerate resource generation.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Each recipe has a target height that needs to be set in the controller before the recipe can start.").withStyle(style -> style.withColor(0x90EE90)))
            .register();

    @Override
    public void addDisplayText(@NotNull List<Component> textList) {
        super.addDisplayText(textList);
    }

    public static void init() {
    }
}
