package net.cu5tmtp.GregECore.gregstuff.GregMachines.machines.euclid;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.IMachineBlockEntity;
import com.gregtechceu.gtceu.api.machine.MachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;
import net.cu5tmtp.GregECore.gregstuff.GregUtils.GregECore;
import net.cu5tmtp.GregECore.gregstuff.GregUtils.notCoreStuff.GregERecipeTypes;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;

import static net.cu5tmtp.GregECore.gregstuff.GregUtils.GregECore.REGISTRATE;

public class GenesisCrucible extends WorkableElectricMultiblockMachine {

    public GenesisCrucible(IMachineBlockEntity holder, Object... args) {
        super(holder, args);
    }

    public static MachineDefinition GENESISCRUCIBLE = REGISTRATE
            .multiblock("genesiscrucible", GenesisCrucible::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeTypes(GregERecipeTypes.NETHERDRILLRIGRECIPE)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT)
            .pattern(definition -> {
                return FactoryBlockPattern.start()
                        .aisle("bbcccccbbbbbbbbbbbbbbbcccccbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbcccccbbbbbbbbbbbbbbbcccccbb")
                        .aisle("bcdddddcbbbbbbbbbbbbbcdddddcb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bcdddddcbbbbbbbbbbbbbcdddddcb")
                        .aisle("cddeeeddcbbbbbbbbbbbcddeeeddc", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbfegefbbbbbbbbbbbbbbbfebefbb", "bbfegefbbbbbbbbbbbbbbbfebefbb", "bbfegefbbbbbbbbbbbbbbbfebefbb", "bbfegefbbbbbbbbbbbbbbbfebefbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbaaaaabbbbbbbbbbbbbbbaaaaabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbaaaaabbbbbbbbbbbbbbbaaaaabb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "cdfeeefdcbbbbbbbbbbbcdfeeefdc")
                        .aisle("cdeeeeedcbbbbbbbbbbbcdeeeeedc", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbfaaafbbbbbbbbbbbbbbbfaaafbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbfaaafbbbbbbbbbbbbbbbfaaafbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbeeeeebbbbbbbbbbbbbbbeeeeebb", "cdeeeeedcbbbbbbbbbbbcdeeeeedc")
                        .aisle("cdeeeeedcbbbbbbbbbbbcdeeeeedc", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbgibigbbbbbbbbbbbbbbbbibigbb", "bbgibigbbbbbbbbbbbbbbbbibigbb", "bbgibigbbbbbbbbbbbbbbbbibigbb", "bbgibigbbbbbbbbbbbbbbbbibigbb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbfaiafbbbbbbbbbbbbbbbfaqafbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbfaiafbbbbbbbbbbbbbbbfaqafbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbeeeeebbbbbbbbbbbbbbbeeeeebb", "cdeeeeedcbbbbbbbbbbbcdeeeeedc")
                        .aisle("cdeeeeedcbbbbbbbbbbbcdeeeeedc", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbfaaafbbbbbbbbbbbbbbbfaaafbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbfaaafbbbbbbbbbbbbbbbfaaafbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbeeeeebbbbbbbbbbbbbbbeeeeebb", "cdeeeeedcbbbbbbbbbbbcdeeeeedc")
                        .aisle("cddeeeddcbbbbbbbbbbbcddeeeddc", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbaaaaabbbbbbbbbbbbbbbaaaaabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbaaaaabbbbbbbbbbbbbbbaaaaabb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "cdfeeefdcbbbbbbbbbbbcdfeeefdc")
                        .aisle("bcdddddmccbbbbbbbbbccmdddddcb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bcdddddmccbbbbbbbbbccmdddddcb")
                        .aisle("bbccccccmcccccccccccmccccccbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbccccccmcccccccccccmccccccbb")
                        .aisle("bbbbbbbccmccdddddccmccbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbccmccdddddccmccbbbbbbb")
                        .aisle("bbbbbbbbccmdnnnnndmccbbbbbbbb", "bbbbbbbbbbbbnnmnnbbbbbbbbbbbb", "bbbbbbbbbbbbnnmnnbbbbbbbbbbbb", "bbbbbbbbbbbbooooobbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbooooobbbbbbbbbbbb", "bbbbbbbbbbbbnnmnnbbbbbbbbbbbb", "bbbbbbbbbbbbnnmnnbbbbbbbbbbbb", "bbbbbbbbccmdnnnnndmccbbbbbbbb")
                        .aisle("bbbbbbbbccdnnnnnnndccbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbonnnnnobbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbbooooobbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbooooobbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbonnnnnobbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbccdnnnnnnndccbbbbbbbb")
                        .aisle("bbbbbbbbcdnnnnnnnnndcbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbonnbbbnnobbbbbbbbbb", "bbbbbbbbbbbnnbbbnnbbbbbbbbbbb", "bbbbbbbbbbbnnbbbnnbbbbbbbbbbb", "bbbbbbbbbbbnnbbbnnbbbbbbbbbbb", "bbbbbbbbbbboonnnoobbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbbooobbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbooobbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbboonnnoobbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbonbbbbbnobbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbcdnnnnnnnnndcbbbbbbbb")
                        .aisle("bbbbbbbbcdnnnnnnnnndcbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbonbbbbbnobbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbonbbbnobbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbonnnobbbbbbbbbbbb", "bbbbbbbbbbbbbnmnbbbbbbbbbbbbb", "bbbbbbbbbbbbbnmnbbbbbbbbbbbbb", "bbbbbbbbbbbbbbmbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbmbbbbbbbbbbbbbb", "bbbbbbbbbbbbbnmnbbbbbbbbbbbbb", "bbbbbbbbbbbbbnmnbbbbbbbbbbbbb", "bbbbbbbbbbbbonnnobbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbonbbbnobbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbonbbbbbnobbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbcdnnnnnnnnndcbbbbbbbb")
                        .aisle("bbbbbbbbcdnnnnnnnnndcbbbbbbbb", "bbbbbbbbbbmbbbbbbbmbbbbbbbbbb", "bbbbbbbbbbmbbbbbbbmbbbbbbbbbb", "bbbbbbbbbbonbbbbbnobbbbbbbbbb", "bbbbbbbbbbbmbbbbbmbbbbbbbbbbb", "bbbbbbbbbbbmbbbbbmbbbbbbbbbbb", "bbbbbbbbbbbmbbbbbmbbbbbbbbbbb", "bbbbbbbbbbbonbbbnobbbbbbbbbbb", "bbbbbbbbbbbbmbbbmbbbbbbbbbbbb", "bbbbbbbbbbbbmbbbmbbbbbbbbbbbb", "bbbbbbbbbbbbmbbbmbbbbbbbbbbbb", "bbbbbbbbbbbbmbbbmbbbbbbbbbbbb", "bbbbbbbbbbbbonnnobbbbbbbbbbbb", "bbbbbbbbbbbbbmnmbbbbbbbbbbbbb", "bbbbbbbbbbbbbmnmbbbbbbbbbbbbb", "bbbbbbbbbbbbbmnmbbbbbbbbbbbbb", "bbbbbbbbbbbbbbmbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbmbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbmbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbmbbbbbbbbbbbbbb", "bbbbbbbbbbbbbmnmbbbbbbbbbbbbb", "bbbbbbbbbbbbbmnmbbbbbbbbbbbbb", "bbbbbbbbbbbbbmnmbbbbbbbbbbbbb", "bbbbbbbbbbbbonnnobbbbbbbbbbbb", "bbbbbbbbbbbbmbbbmbbbbbbbbbbbb", "bbbbbbbbbbbbmbbbmbbbbbbbbbbbb", "bbbbbbbbbbbbmbbbmbbbbbbbbbbbb", "bbbbbbbbbbbbmbbbmbbbbbbbbbbbb", "bbbbbbbbbbbonbbbnobbbbbbbbbbb", "bbbbbbbbbbbmbbbbbmbbbbbbbbbbb", "bbbbbbbbbbbmbbbbbmbbbbbbbbbbb", "bbbbbbbbbbbmbbbbbmbbbbbbbbbbb", "bbbbbbbbbbonbbbbbnobbbbbbbbbb", "bbbbbbbbbbmbbbbbbbmbbbbbbbbbb", "bbbbbbbbbbmbbbbbbbmbbbbbbbbbb", "bbbbbbbbcdnnnnnnnnndcbbbbbbbb")
                        .aisle("bbbbbbbbcdnnnnnnnnndcbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbonbbbbbnobbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbonbbbnobbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbonnnobbbbbbbbbbbb", "bbbbbbbbbbbbbnmnbbbbbbbbbbbbb", "bbbbbbbbbbbbbnmnbbbbbbbbbbbbb", "bbbbbbbbbbbbbbmbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbmbbbbbbbbbbbbbb", "bbbbbbbbbbbbbnmnbbbbbbbbbbbbb", "bbbbbbbbbbbbbnmnbbbbbbbbbbbbb", "bbbbbbbbbbbbonnnobbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbbnbbbnbbbbbbbbbbbb", "bbbbbbbbbbbonbbbnobbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbonbbbbbnobbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbcdnnnnnnnnndcbbbbbbbb")
                        .aisle("bbbbbbbbcdnnnnnnnnndcbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbonnbbbnnobbbbbbbbbb", "bbbbbbbbbbbnnbbbnnbbbbbbbbbbb", "bbbbbbbbbbbnnbbbnnbbbbbbbbbbb", "bbbbbbbbbbbnnbbbnnbbbbbbbbbbb", "bbbbbbbbbbboonnnoobbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbbooobbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbooobbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbbbpnmnpbbbbbbbbbbbb", "bbbbbbbbbbboonnnoobbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbonbbbbbnobbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbbbnbbbbbbbnbbbbbbbbbb", "bbbbbbbbcdnnnnnnnnndcbbbbbbbb")
                        .aisle("bbbbbbbbccdnnnnnnndccbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbonnnnnobbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbbooooobbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbooooobbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbpnnmnnpbbbbbbbbbbb", "bbbbbbbbbbbonnnnnobbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbbbbnbbbbbnbbbbbbbbbbb", "bbbbbbbbccdnnnnnnndccbbbbbbbb")
                        .aisle("bbbbbbbbccmdnnnnndmccbbbbbbbb", "bbbbbbbbbbbbnnmnnbbbbbbbbbbbb", "bbbbbbbbbbbbnnmnnbbbbbbbbbbbb", "bbbbbbbbbbbbooooobbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbooooobbbbbbbbbbbb", "bbbbbbbbbbbbnnmnnbbbbbbbbbbbb", "bbbbbbbbbbbbnnmnnbbbbbbbbbbbb", "bbbbbbbbccmdnnnnndmccbbbbbbbb")
                        .aisle("bbbbbbbccmccdddddccmccbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbccmccdddddccmccbbbbbbb")
                        .aisle("bbccccccmccccczcccccmccccccbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbccccccmcccccccccccmccbbbbbb")
                        .aisle("bcdddddmccbbbbbbbbbccmdddddcb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bcdddddmccbbbbbbbbbccmdddddbb")
                        .aisle("cddeeeddcbbbbbbbbbbbcddeeeddc", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbaaaaabbbbbbbbbbbbbbbaaaaabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbaaaaabbbbbbbbbbbbbbbaaaaabb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "cdfeeefdcbbbbbbbbbbbcdfeeefdb")
                        .aisle("cdeeeeedcbbbbbbbbbbbcdeeeeedc", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbfaaafbbbbbbbbbbbbbbbfaaafbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbfaaafbbbbbbbbbbbbbbbfaaafbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbeeeeebbbbbbbbbbbbbbbeeeeebb", "cdeeeeedcbbbbbbbbbbbbdeeeeedb")
                        .aisle("cdeeeeedcbbbbbbbbbbbcdeeeeedc", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbfakafbbbbbbbbbbbbbbbfalafbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbfakafbbbbbbbbbbbbbbbfalafbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbbjbjbbbbbbbbbbbbbbbbbjbjbbb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbgibigbbbbbbbbbbbbbbbgibigbb", "bbeeeeebbbbbbbbbbbbbbbeeeeebb", "cdeeeeedcbbbbbbbbbbbbdeeeeedb")
                        .aisle("cdeeeeedcbbbbbbbbbbbcdeeeeedc", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbfaaafbbbbbbbbbbbbbbbfaaafbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbabbbabbbbbbbbbbbbbbbabbbabb", "bbfaaafbbbbbbbbbbbbbbbfaaafbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbbjjjbbbbbbbbbbbbbbbbbjjjbbb", "bbfbbbfbbbbbbbbbbbbbbbfbbbfbb", "bbebbbebbbbbbbbbbbbbbbebbbebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbebibebbbbbbbbbbbbbbbebibebb", "bbeeeeebbbbbbbbbbbbbbbeeeeebb", "cdeeeeedcbbbbbbbbbbbbdeeeeedb")
                        .aisle("cddeeeddcbbbbbbbbbbbcddeeeddc", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbaaaaabbbbbbbbbbbbbbbaaaaabb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbaaaaabbbbbbbbbbbbbbbaaaaabb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhbbbhbbbbbbbbbbbbbbbhbbbhbb", "bbhfffhbbbbbbbbbbbbbbbhfffhbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfegefbbbbbbbbbbbbbbbfegefbb", "bbfeeefbbbbbbbbbbbbbbbfeeefbb", "cdfeeefdcbbbbbbbbbbbbdfeeefdb")
                        .aisle("bcdddddcbbbbbbbbbbbbbcdddddcb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "babbbbbabbbbbbbbbbbbbabbbbbab", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bcdddddcbbbbbbbbbbbbbbdddddbb")
                        .aisle("bbcccccbbbbbbbbbbbbbbbcccccbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "abbbbbbbabbbbbbbbbbbabbbbbbba", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "bbcccccbbbbbbbbbbbbbbbbbbbbbb")

                        .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:atomic_casing"))))
                        .where("b", Predicates.any())
                        .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("kubejs:machine_casing_tiled_gray")))
                                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2)))
                        .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:high_temperature_smelting_casing"))))
                        .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:large_scale_assembler_casing"))))
                        .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:sturdy_machine_casing"))))
                        .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:fusion_glass"))))
                        .where("h", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:nebulon_alpha_frame"))))
                        .where("i", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("kubejs:machine_casing_block_purple"))))
                        .where("j", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gregecore:awakened_draconium_coil"))))
                        .where("k", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("kubejs:machine_casing_block_red"))))
                        .where("l", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("kubejs:machine_casing_block_orange"))))
                        .where("m", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:superconducting_coil"))))
                        .where("n", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stress_proof_casing"))))
                        .where("o", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:industrial_steam_casing"))))
                        .where("p", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:neutronium_frame"))))
                        .where("q", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("kubejs:machine_casing_block_lime"))))
                        .where("z", Predicates.controller(Predicates.blocks(definition.get())))
                        .where("#", Predicates.any())
                        .build();
            })
            .workableCasingModel(
                    GregECore.id("block/machine_casing_tiled_gray"),
                    GTCEu.id("gtceu:block/multiblock/distillation_tower")
            )
            .register();

    public static void init() {
    }
}